#!/usr/bin/env bash

set -e

run_dependencies() {
  echo "dependencies"
  go mod tidy
}

run_format() {
  echo "format"
  go fmt ./...
}

run_linter() {
  echo "linter"
  revive -formatter friendly ./...
}

run_vet() {
  echo "vet"
  go vet ./...
}

run_error_checking() {
  echo "error checking"
  errcheck -ignoretests ./...
}

run_static_analysis() {
  echo "static analysis"
  staticcheck $(go list ./... | grep -v '/examples')
}

run_gosec() {
  echo "gosec"
  gosec -quiet -exclude-dir=examples -exclude=G404,G112 ./...
}

# run_gocycle() {
#   echo "gocycle"
#   gocyclo -over 10 .
# }

for stage in dependencies format linter vet error_checking static_analysis gosec; do
  "run_${stage}"
done

exit 0
