package sentinel

import (
	"github.com/mcwalrus/go-sentinel/circuit"
	"github.com/prometheus/client_golang/prometheus"
)

// ControlFunc is a function that receives the execution phase and returns true to stop execution.
// Use [circuit.WhenClosed] to create a ControlFunc for graceful shutdown.
//
// Example usage:
//
//	done := make(chan struct{})
//	observer := sentinel.NewObserver(nil,
//	    sentinel.WithControl(circuit.WhenClosed(done)),
//	)
type ControlFunc = circuit.Control

// config defines the configuration for a [Observer].
type config struct {
	namespace    string
	subsystem    string
	description  string
	buckets      []float64
	constLabels  prometheus.Labels
	metricFilter map[string]bool

	// Per-metric enable flags for the composable metrics builder API.
	// Zero value (false) means disabled; opt-in by default.
	enableInFlight  bool
	enableSuccess   bool
	enableErrors    bool
	enableFailures  bool
	enablePanics    bool
	enableRetries   bool
	enableTimeouts  bool
	enableDurations bool
	enablePending   bool

	// DurationBuckets holds histogram bucket boundaries for duration metrics.
	// Replaces the durationBuckets constructor parameter in the composable API.
	DurationBuckets []float64

	// ErrorLabeler maps errors to prometheus label sets for WithErrorLabels() support.
	ErrorLabeler func(err error) prometheus.Labels

	// maxConcurrency limits the number of goroutines in the async worker pool.
	// Zero means unlimited.
	maxConcurrency int

	// control is the execution control handler set via WithControl().
	control ControlFunc
}

// setupConfig sets up the configuration
func setupConfig(durationBuckets []float64, opts ...ObserverOption) config {
	cfg := config{
		namespace:    "",
		subsystem:    "",
		description:  "tasks",
		buckets:      durationBuckets,
		metricFilter: make(map[string]bool),
	}

	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}

	if cfg.subsystem == "" && cfg.namespace == "" {
		cfg.subsystem = "sentinel"
	}
	if cfg.description == "" {
		cfg.description = "tasks"
	}
	if len(cfg.metricFilter) == 0 {
		cfg.metricFilter = defaultMetricFilter()
	}

	return cfg
}

// ObserverOption defines prometheus metrics options for an [Observer].
// Options are provided to [NewObserver] on setting up the Observer.
type ObserverOption func(*config)

// WithNamespace sets the prometheus namespace for all metrics generated by this observer.
// For example, "myapp" with no subsystem results in metrics like "myapp_success_total".
// If empty with subsystem, no namespace prefix is used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithNamespace("myapp"),
//	)
func WithNamespace(namespace string) ObserverOption {
	return func(cfg *config) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the prometheus subsystem for all metrics generated by this observer.
// For example, "workers" with no namespace results in metrics like "workers_success_total".
// If empty with namespace, defaults to "sentinel" if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSubsystem("workers"),
//	)
func WithSubsystem(subsystem string) ObserverOption {
	return func(cfg *config) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated prometheus
// metrics to describe the tasks being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" to convey a generic process if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDescription("background processes"),
//	)
func WithDescription(description string) ObserverOption {
	return func(cfg *config) {
		cfg.description = description
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By convention, ConstLabels are not a recommended practice for Prometheus metrics.
// For more information, please refer to [prometheus.Opts].ConstLabels documentation.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithConstLabels(
//	        prometheus.Labels{"env": "production"},
//	    ),
//	)
func WithConstLabels(labels prometheus.Labels) ObserverOption {
	return func(cfg *config) {
		cfg.constLabels = labels
	}
}

// Metric names that can be enabled/disabled
const (
	MetricInFlight  = "inFlight"
	MetricSuccesses = "successes"
	MetricFailures  = "failures"
	MetricErrors    = "errors"
	MetricTimeouts  = "timeouts"
	MetricPanics    = "panics"
	MetricDurations = "durations"
	MetricRetries   = "retries"
	MetricPending   = "pending"
)

func defaultMetricFilter() map[string]bool {
	return map[string]bool{
		MetricInFlight:  true,
		MetricSuccesses: true,
		MetricFailures:  true,
		MetricErrors:    true,
		MetricTimeouts:  true,
		MetricPanics:    true,
		MetricDurations: true,
		MetricRetries:   true,
	}
}

// WithMetrics enables only the specified metrics for export.
// If not called, all metrics are enabled by default.
// Metrics that are not included will not be registered or exported.
//
// Example usage:
//
//	// Only export successes and failures
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMetrics(
//	        sentinel.MetricSuccesses,
//	        sentinel.MetricFailures,
//	    ),
//	)
//
//	// Export all metrics except durations
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMetrics(
//	        sentinel.MetricInFlight,
//	        sentinel.MetricSuccesses,
//	        sentinel.MetricFailures,
//	        sentinel.MetricErrors,
//	        sentinel.MetricTimeouts,
//	        sentinel.MetricPanics,
//	        sentinel.MetricRetries,
//	    ),
//	)
func WithMetrics(metricNames ...string) ObserverOption {
	return func(cfg *config) {
		if cfg.metricFilter == nil {
			cfg.metricFilter = make(map[string]bool)
		}
		for _, name := range metricNames {
			cfg.metricFilter[name] = true
		}
	}
}

// WithInFlightMetrics enables the in_flight gauge metric for the Observer.
// The in_flight gauge tracks the number of tasks currently executing.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithInFlightMetrics(),
//	)
func WithInFlightMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableInFlight = true
	}
}

// WithSuccessMetrics enables the success_total counter metric for the Observer.
// The success_total counter increments each time a task completes without error.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSuccessMetrics(),
//	)
func WithSuccessMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableSuccess = true
	}
}

// WithErrorMetrics enables the errors_total and failures_total counter metrics for the Observer.
// The errors_total counter increments each time a task returns an error (including retries and panics).
// The failures_total counter increments each time a task exhausts all retry attempts or fails permanently.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithErrorMetrics(),
//	)
func WithErrorMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableErrors = true
		cfg.enableFailures = true
	}
}

// WithTimeoutMetrics enables the timeouts_total counter metric for the Observer.
// The timeouts_total counter increments each time a task returns context.DeadlineExceeded.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithTimeoutMetrics(),
//	)
func WithTimeoutMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableTimeouts = true
	}
}

// WithErrorLabels sets a labeler function that maps errors to Prometheus label sets.
// When a task fails, the labeler is called with the error to produce labels for the
// errors_total metric. If the labeler panics, errors_total is incremented without
// labels and panics_total is incremented to record the callback failure.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithErrorLabels(func(err error) prometheus.Labels {
//	        return prometheus.Labels{"kind": classifyError(err)}
//	    }),
//	)
func WithErrorLabels(labeler func(err error) prometheus.Labels) ObserverOption {
	return func(cfg *config) {
		cfg.ErrorLabeler = labeler
	}
}

// WithQueueMetrics enables the pending_total gauge metric for the Observer.
// The pending_total gauge tracks the number of tasks waiting for a pool slot
// when using [Observer.Submit] or [Observer.SubmitFunc] with [WithMaxConcurrency].
// Without this option, pending_total is not registered or tracked.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithQueueMetrics(),
//	    sentinel.WithMaxConcurrency(5),
//	)
func WithQueueMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enablePending = true
		cfg.metricFilter[MetricPending] = true
	}
}

// WithMaxConcurrency limits the number of concurrent goroutines in the async
// worker pool used by [Observer.Submit] and [Observer.SubmitFunc]. When combined
// with [WithQueueMetrics], tasks waiting for a pool slot are tracked by pending_total.
// Zero or negative values are ignored (unlimited concurrency).
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMaxConcurrency(10),
//	    sentinel.WithQueueMetrics(),
//	)
func WithMaxConcurrency(n int) ObserverOption {
	return func(cfg *config) {
		if n > 0 {
			cfg.maxConcurrency = n
		}
	}
}

// WithControl sets an execution control handler that can reject new requests or retry attempts.
// Use [circuit.WhenClosed] for graceful shutdown.
//
// The control function receives the [circuit.ExecutionPhase] and returns true to stop execution.
// When set, the control is checked before each new request ([circuit.PhaseNewRequest]) and before
// each retry attempt ([circuit.PhaseRetry]). If control returns true, the execution is stopped
// and [ErrControlBreaker] is returned.
//
// Example usage:
//
//	done := make(chan struct{})
//	observer := sentinel.NewObserver(nil,
//	    sentinel.WithControl(circuit.WhenClosed(done)),
//	)
//	// Later, to gracefully stop accepting new tasks:
//	close(done)
func WithControl(fn ControlFunc) ObserverOption {
	return func(cfg *config) {
		cfg.control = fn
	}
}
