package sentinel

import (
	"errors"
	"slices"
	"time"

	"github.com/mcwalrus/go-sentinel/v2/circuit"
	"github.com/mcwalrus/go-sentinel/v2/retry"
	"github.com/prometheus/client_golang/prometheus"
)

// ControlFunc is a function that receives the execution phase and returns true to stop execution.
// Use [circuit.WhenClosed] to create a ControlFunc for graceful shutdown.
//
// Example usage:
//
//	done := make(chan struct{})
//	observer := sentinel.NewObserver(nil,
//	    sentinel.WithControl(circuit.WhenClosed(done)),
//	)
type ControlFunc = circuit.Control

// config defines the configuration for a [Observer].
type config struct {
	namespace    string
	subsystem    string
	description  string
	constLabels  prometheus.Labels
	metricFilter map[string]bool

	// Per-metric enable flags for the composable metrics builder API.
	// Zero value (false) means disabled; opt-in by default.
	enableInFlight  bool
	enableSuccess   bool
	enableErrors    bool
	enableFailures  bool
	enablePanics    bool
	enableRetries   bool
	enableTimeouts  bool
	enableDurations bool
	enablePending   bool

	// DurationBuckets holds histogram bucket boundaries for duration metrics.
	// Replaces the durationBuckets constructor parameter in the composable API.
	DurationBuckets []float64

	// ErrorLabeler maps errors to prometheus label sets for WithErrorLabels() support.
	ErrorLabeler func(err error) prometheus.Labels

	// errorLabelNames holds the sorted label key names discovered from a sample call to ErrorLabeler.
	// Non-nil only when WithErrorLabels is set and the labeler returns a non-empty label set.
	errorLabelNames []string

	// timeout sets a context deadline for each task execution.
	// Zero means no timeout is applied.
	timeout time.Duration

	// maxConcurrency limits the number of goroutines in the async worker pool.
	// Zero means unlimited.
	maxConcurrency int

	// control is the execution control handler set via WithControl().
	control ControlFunc

	// retrier is the observer-level retry handler set via WithRetrier().
	retrier retry.Retrier
}

// setupConfig sets up the configuration
func setupConfig(opts ...ObserverOption) config {
	cfg := config{
		namespace:    "",
		subsystem:    "",
		description:  "tasks",
		metricFilter: make(map[string]bool),
	}

	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}

	if cfg.subsystem == "" && cfg.namespace == "" {
		cfg.subsystem = "sentinel"
	}
	if cfg.description == "" {
		cfg.description = "tasks"
	}

	// Translate typed enable flags into metricFilter entries.
	// This allows WithXxxMetrics() options to control which metrics are registered.
	if cfg.enableInFlight {
		cfg.metricFilter[MetricInFlight] = true
	}
	if cfg.enableSuccess {
		cfg.metricFilter[MetricSuccesses] = true
	}
	if cfg.enableErrors {
		cfg.metricFilter[MetricErrors] = true
	}
	if cfg.enableFailures {
		cfg.metricFilter[MetricFailures] = true
	}
	if cfg.enablePanics {
		cfg.metricFilter[MetricPanics] = true
	}
	if cfg.enableRetries {
		cfg.metricFilter[MetricRetries] = true
	}
	if cfg.enableTimeouts {
		cfg.metricFilter[MetricTimeouts] = true
	}
	if cfg.enableDurations {
		cfg.metricFilter[MetricDurations] = true
		if len(cfg.DurationBuckets) == 0 {
			cfg.DurationBuckets = prometheus.DefBuckets
		}
	}
	if cfg.enablePending {
		cfg.metricFilter[MetricPending] = true
	}

	// Fall back to all metrics only if neither WithMetrics() nor WithXxxMetrics() was used.
	if len(cfg.metricFilter) == 0 {
		cfg.metricFilter = defaultMetricFilter()
	}

	return cfg
}

// ObserverOption defines prometheus metrics options for an [Observer].
// Options are provided to [NewObserver] on setting up the Observer.
type ObserverOption func(*config)

// WithNamespace sets the prometheus namespace for all metrics generated by this observer.
// For example, "myapp" with no subsystem results in metrics like "myapp_success_total".
// If empty with subsystem, no namespace prefix is used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithNamespace("myapp"),
//	)
func WithNamespace(namespace string) ObserverOption {
	return func(cfg *config) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the prometheus subsystem for all metrics generated by this observer.
// For example, "workers" with no namespace results in metrics like "workers_success_total".
// If empty with namespace, defaults to "sentinel" if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSubsystem("workers"),
//	)
func WithSubsystem(subsystem string) ObserverOption {
	return func(cfg *config) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated prometheus
// metrics to describe the tasks being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" to convey a generic process if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDescription("background processes"),
//	)
func WithDescription(description string) ObserverOption {
	return func(cfg *config) {
		cfg.description = description
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By convention, ConstLabels are not a recommended practice for Prometheus metrics.
// For more information, please refer to [prometheus.Opts].ConstLabels documentation.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithConstLabels(
//	        prometheus.Labels{"env": "production"},
//	    ),
//	)
func WithConstLabels(labels prometheus.Labels) ObserverOption {
	return func(cfg *config) {
		cfg.constLabels = labels
	}
}

// Metric names that can be enabled/disabled
const (
	MetricInFlight  = "inFlight"
	MetricSuccesses = "successes"
	MetricFailures  = "failures"
	MetricErrors    = "errors"
	MetricTimeouts  = "timeouts"
	MetricPanics    = "panics"
	MetricDurations = "durations"
	MetricRetries   = "retries"
	MetricPending   = "pending"
)

func defaultMetricFilter() map[string]bool {
	return map[string]bool{
		MetricInFlight:  true,
		MetricSuccesses: true,
		MetricFailures:  true,
		MetricErrors:    true,
		MetricTimeouts:  true,
		MetricPanics:    true,
		MetricDurations: true,
		MetricRetries:   true,
	}
}

// WithMetrics enables only the specified metrics for export using string-based metric names.
// If not called, all metrics are enabled by default.
// Metrics that are not included will not be registered or exported.
//
// Deprecated: Use the typed WithXxxMetrics() options instead (e.g. WithInFlightMetrics(),
// WithSuccessMetrics(), WithErrorMetrics()). WithMetrics() will be removed in a future release.
//
// Example usage:
//
//	// Only export successes and failures
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMetrics(
//	        sentinel.MetricSuccesses,
//	        sentinel.MetricFailures,
//	    ),
//	)
func WithMetrics(metricNames ...string) ObserverOption {
	return func(cfg *config) {
		if cfg.metricFilter == nil {
			cfg.metricFilter = make(map[string]bool)
		}
		for _, name := range metricNames {
			cfg.metricFilter[name] = true
		}
	}
}

// WithInFlightMetrics enables the in_flight gauge metric for the Observer.
// The in_flight gauge tracks the number of tasks currently executing.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithInFlightMetrics(),
//	)
func WithInFlightMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableInFlight = true
	}
}

// WithSuccessMetrics enables the success_total counter metric for the Observer.
// The success_total counter increments each time a task completes without error.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSuccessMetrics(),
//	)
func WithSuccessMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableSuccess = true
	}
}

// WithErrorMetrics enables the errors_total counter metric for the Observer.
// The errors_total counter increments each time a task returns an error (including retries and panics).
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithErrorMetrics(),
//	)
func WithErrorMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableErrors = true
	}
}

// WithTimeoutMetrics enables the timeouts_total counter metric for the Observer.
// The timeouts_total counter increments each time a task returns context.DeadlineExceeded.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithTimeoutMetrics(),
//	)
func WithTimeoutMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableTimeouts = true
	}
}

// WithPanicMetrics enables the panics_total counter metric for the Observer.
// The panics_total counter increments each time a task or control handler panics.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithPanicMetrics(),
//	)
func WithPanicMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enablePanics = true
	}
}

// WithRetryMetrics enables the retries_total and failures_total counter metrics for the Observer.
// The retries_total counter increments each time a task is retried after a failure.
// The failures_total counter increments each time a task exhausts all retry attempts or fails permanently.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithRetryMetrics(),
//	)
func WithRetryMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableRetries = true
		cfg.enableFailures = true
	}
}

// WithErrorLabels sets a labeler function that maps errors to Prometheus label sets.
// When a task fails, the labeler is called with the error to produce labels for the
// errors_total Counter metric. The label keys are discovered by calling the labeler
// once at construction time with an empty error; the Counter is registered with those
// label names. If the labeler panics, errors_total is incremented without labels and
// panics_total is incremented to record the callback failure.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithErrorLabels(func(err error) prometheus.Labels {
//	        return prometheus.Labels{"kind": classifyError(err)}
//	    }),
//	)
func WithErrorLabels(labeler func(err error) prometheus.Labels) ObserverOption {
	return func(cfg *config) {
		cfg.ErrorLabeler = labeler
		if labeler == nil {
			return
		}
		// Discover label names from a sample call
		func() {
			defer func() { _ = recover() }()
			sampleLabels := labeler(errors.New(""))
			if len(sampleLabels) == 0 {
				return
			}
			names := make([]string, 0, len(sampleLabels))
			for k := range sampleLabels {
				names = append(names, k)
			}
			slices.Sort(names)
			cfg.errorLabelNames = names
		}()
	}
}

// WithDurationMetrics enables the durations_seconds histogram metric for the Observer.
// The histogram tracks the execution duration of each task. If buckets is nil or empty,
// prometheus.DefBuckets is used as the default bucket set.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDurationMetrics([]float64{0.1, 0.25, 0.5, 1.0, 2.5, 5.0}),
//	)
func WithDurationMetrics(buckets []float64) ObserverOption {
	return func(cfg *config) {
		cfg.enableDurations = true
		cfg.DurationBuckets = buckets
	}
}

// WithQueueMetrics enables the pending_total gauge metric for the Observer.
// The pending_total gauge tracks the number of tasks waiting for a pool slot
// when using [Observer.Submit] or [Observer.SubmitFunc] with [WithMaxConcurrency].
// Without this option, pending_total is not registered or tracked.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithQueueMetrics(),
//	    sentinel.WithMaxConcurrency(5),
//	)
func WithQueueMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enablePending = true
		cfg.metricFilter[MetricPending] = true
	}
}

// WithMaxConcurrency limits the number of concurrent goroutines in the async
// worker pool used by [Observer.Submit] and [Observer.SubmitFunc]. When combined
// with [WithQueueMetrics], tasks waiting for a pool slot are tracked by pending_total.
// Zero or negative values are ignored (unlimited concurrency).
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMaxConcurrency(10),
//	    sentinel.WithQueueMetrics(),
//	)
func WithMaxConcurrency(n int) ObserverOption {
	return func(cfg *config) {
		if n > 0 {
			cfg.maxConcurrency = n
		}
	}
}

// WithTimeout sets a context deadline applied to each task execution by this Observer.
// The timeout is applied per attempt (including retries). When a task exceeds the deadline,
// the context passed to the task function is cancelled with context.DeadlineExceeded.
// Zero or negative values are ignored (no timeout applied).
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithTimeout(5*time.Second),
//	)
func WithTimeout(d time.Duration) ObserverOption {
	return func(cfg *config) {
		if d > 0 {
			cfg.timeout = d
		}
	}
}

// WithControl sets an execution control handler that can reject new requests or retry attempts.
// Use [circuit.WhenClosed] for graceful shutdown.
//
// The control function receives the [circuit.ExecutionPhase] and returns true to stop execution.
// When set, the control is checked before each new request ([circuit.PhaseNewRequest]) and before
// each retry attempt ([circuit.PhaseRetry]). If control returns true, the execution is stopped
// and [ErrControlBreaker] is returned.
//
// Example usage:
//
//	done := make(chan struct{})
//	observer := sentinel.NewObserver(nil,
//	    sentinel.WithControl(circuit.WhenClosed(done)),
//	)
//	// Later, to gracefully stop accepting new tasks:
//	close(done)
func WithControl(fn ControlFunc) ObserverOption {
	return func(cfg *config) {
		cfg.control = fn
	}
}

// WithRetrier sets an observer-level [retry.Retrier] that handles all retry logic
// for tasks executed by this Observer. When set, it replaces the per-task
// MaxRetries/RetryStrategy/RetryBreaker triplet in [ObserverConfig].
//
// If not set, tasks are executed without retries unless MaxRetries is configured
// on the per-task [ObserverConfig].
//
// Example usage:
//
//	observer := sentinel.NewObserver(nil,
//	    sentinel.WithRetrier(retry.DefaultRetrier{
//	        WaitStrategy: retry.Exponential(10 * time.Millisecond),
//	        MaxRetries:   3,
//	    }),
//	)
func WithRetrier(r retry.Retrier) ObserverOption {
	return func(cfg *config) {
		cfg.retrier = r
	}
}
