package sentinel

import "github.com/prometheus/client_golang/prometheus"

// config defines the configuration for a [Observer].
type config struct {
	namespace    string
	subsystem    string
	description  string
	buckets      []float64
	constLabels  prometheus.Labels
	metricFilter map[string]bool

	// Per-metric enable flags for the composable metrics builder API.
	// Zero value (false) means disabled; opt-in by default.
	enableInFlight  bool
	enableSuccess   bool
	enableErrors    bool
	enableFailures  bool
	enablePanics    bool
	enableRetries   bool
	enableTimeouts  bool
	enableDurations bool
	enablePending   bool

	// DurationBuckets holds histogram bucket boundaries for duration metrics.
	// Replaces the durationBuckets constructor parameter in the composable API.
	DurationBuckets []float64

	// ErrorLabeler maps errors to prometheus label sets for WithErrorLabels() support.
	ErrorLabeler func(err error) prometheus.Labels

	// maxConcurrency limits the number of goroutines in the async worker pool.
	// Zero means unlimited.
	maxConcurrency int
}

// setupConfig sets up the configuration
func setupConfig(durationBuckets []float64, opts ...ObserverOption) config {
	cfg := config{
		namespace:    "",
		subsystem:    "",
		description:  "tasks",
		buckets:      durationBuckets,
		metricFilter: make(map[string]bool),
	}

	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}

	if cfg.subsystem == "" && cfg.namespace == "" {
		cfg.subsystem = "sentinel"
	}
	if cfg.description == "" {
		cfg.description = "tasks"
	}
	if len(cfg.metricFilter) == 0 {
		cfg.metricFilter = defaultMetricFilter()
	}

	return cfg
}

// ObserverOption defines prometheus metrics options for an [Observer].
// Options are provided to [NewObserver] on setting up the Observer.
type ObserverOption func(*config)

// WithNamespace sets the prometheus namespace for all metrics generated by this observer.
// For example, "myapp" with no subsystem results in metrics like "myapp_success_total".
// If empty with subsystem, no namespace prefix is used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithNamespace("myapp"),
//	)
func WithNamespace(namespace string) ObserverOption {
	return func(cfg *config) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the prometheus subsystem for all metrics generated by this observer.
// For example, "workers" with no namespace results in metrics like "workers_success_total".
// If empty with namespace, defaults to "sentinel" if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSubsystem("workers"),
//	)
func WithSubsystem(subsystem string) ObserverOption {
	return func(cfg *config) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated prometheus
// metrics to describe the tasks being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" to convey a generic process if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDescription("background processes"),
//	)
func WithDescription(description string) ObserverOption {
	return func(cfg *config) {
		cfg.description = description
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By convention, ConstLabels are not a recommended practice for Prometheus metrics.
// For more information, please refer to [prometheus.Opts].ConstLabels documentation.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithConstLabels(
//	        prometheus.Labels{"env": "production"},
//	    ),
//	)
func WithConstLabels(labels prometheus.Labels) ObserverOption {
	return func(cfg *config) {
		cfg.constLabels = labels
	}
}

// Metric names that can be enabled/disabled
const (
	MetricInFlight  = "inFlight"
	MetricSuccesses = "successes"
	MetricFailures  = "failures"
	MetricErrors    = "errors"
	MetricTimeouts  = "timeouts"
	MetricPanics    = "panics"
	MetricDurations = "durations"
	MetricRetries   = "retries"
	MetricPending   = "pending"
)

func defaultMetricFilter() map[string]bool {
	return map[string]bool{
		MetricInFlight:  true,
		MetricSuccesses: true,
		MetricFailures:  true,
		MetricErrors:    true,
		MetricTimeouts:  true,
		MetricPanics:    true,
		MetricDurations: true,
		MetricRetries:   true,
		MetricPending:   true,
	}
}

// WithMetrics enables only the specified metrics for export.
// If not called, all metrics are enabled by default.
// Metrics that are not included will not be registered or exported.
//
// Example usage:
//
//	// Only export successes and failures
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMetrics(
//	        sentinel.MetricSuccesses,
//	        sentinel.MetricFailures,
//	    ),
//	)
//
//	// Export all metrics except durations
//	observer := sentinel.NewObserver(
//	    nil,
//	    sentinel.WithMetrics(
//	        sentinel.MetricInFlight,
//	        sentinel.MetricSuccesses,
//	        sentinel.MetricFailures,
//	        sentinel.MetricErrors,
//	        sentinel.MetricTimeouts,
//	        sentinel.MetricPanics,
//	        sentinel.MetricRetries,
//	    ),
//	)
func WithMetrics(metricNames ...string) ObserverOption {
	return func(cfg *config) {
		if cfg.metricFilter == nil {
			cfg.metricFilter = make(map[string]bool)
		}
		for _, name := range metricNames {
			cfg.metricFilter[name] = true
		}
	}
}

// WithInFlightMetrics enables the in_flight gauge metric for the Observer.
// The in_flight gauge tracks the number of tasks currently executing.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithInFlightMetrics(),
//	)
func WithInFlightMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableInFlight = true
	}
}

// WithSuccessMetrics enables the success_total counter metric for the Observer.
// The success_total counter increments each time a task completes without error.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSuccessMetrics(),
//	)
func WithSuccessMetrics() ObserverOption {
	return func(cfg *config) {
		cfg.enableSuccess = true
	}
}
