// Package sentinel provides reliability handling and observability monitoring for Go applications.
// It wraps task execution with Prometheus metrics, observing errors, panic occurrences, retries,
// and timeouts — making critical routines safe, measurable, and reliable.
package sentinel

import (
	"context"
	"errors"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

// ObserverConfig defines the configuration of an [Observer] instance,
// including Prometheus metrics naming and histogram bucket configuration.
type ObserverConfig struct {
	// Namespace is the Prometheus namespace for all metrics generated by this observer.
	// For example, "myapp" results in metrics like "myapp_sentinel_successes_total".
	// If empty, no namespace prefix is used.
	Namespace string

	// Subsystem is the Prometheus subsystem for all metrics generated by this observer.
	// For example, "workers" results in metrics like "workers_successes_total".
	// Defaults to "sentinel" if not specified.
	Subsystem string

	// Description is used in the help text for generated metrics to describe what type
	// of tasks are being observed. For example, "background processes" results in help
	// text like: "Number of successes from observed background processes". Defaults to
	// "tasks".
	Description string

	// BucketDurations defines the histogram buckets for task duration metrics.
	// Each recorded runtime duration is assigned within one of the specified buckets.
	// Please refer to [prometheus.HistogramOpts].Buckets for more information.
	BucketDurations []float64

	// ConstLabels are used to attach fixed labels to these metrics. By default, no labels
	// are attached. Please refer to [prometheus.Opts].ConstLabels for more information.
	ConstLabels prometheus.Labels

	// DefaultTaskConfig specifies the default [TaskConfig] for calls to [Observer.RunFunc].
	// If not specified, a basic task configuration of panic recovery without retry attempts
	// will be used.
	DefaultTaskConfig *TaskConfig
}

// DefaultConfig returns the default configuration for an [Observer].
// It is recommended to use your own configuration to manage metrics.
func DefaultConfig() ObserverConfig {
	return ObserverConfig{
		Namespace:       "",
		Subsystem:       "sentinel",
		Description:     "tasks",
		BucketDurations: []float64{0.01, 0.1, 1, 5, 10, 30, 60, 120},
	}
}

// Observer monitors and measures task executions, collecting Prometheus metrics
// for successes, failures, timeouts, panics, retries, and execution durations.
// It provides methods to execute tasks with various configuration options.
type Observer struct {
	cfg     ObserverConfig
	metrics *metrics
}

// NewObserver creates a new Observer instance with the specified configuration.
// The Observer will need to be registered with a Prometheus registry to expose metrics.
// Please refer to [Observer.MustRegister] and [Observer.Register] for more information.
func NewObserver(cfg ObserverConfig) *Observer {
	if cfg.Subsystem == "" && cfg.Namespace == "" {
		cfg.Subsystem = "sentinel"
	}
	if cfg.Description == "" {
		cfg.Description = "tasks"
	}
	return &Observer{
		cfg:     cfg,
		metrics: newMetrics(cfg),
	}
}

// Register registers all Observer metrics with the provided Prometheus registry.
// Use [Observer.MustRegister] if you want the program to panic on registration conflicts.
func (o *Observer) Register(registry prometheus.Registerer) error {
	return o.metrics.Register(registry)
}

// MustRegister registers all Observer metrics with the provided Prometheus registry.
// This method panics if any metric registration failures. Use [Observer.Register] if you prefer
// to handle registration errors gracefully.
func (o *Observer) MustRegister(registry prometheus.Registerer) {
	o.metrics.MustRegister(registry)
}

// Run executes a function with the specified task configuration and observes its execution.
// All execution metrics (duration, success/failure, retries, etc) will be automatically recorded.
// If a [context.DeadlineExceeded] error is returne by fn(), it is recorded as a timeout error.
// When cfg.RecoverPanics is true, returns ErrPanicOccurred if a panic occurs and is recovered.
func (o *Observer) Run(cfg TaskConfig, fn func(ctx context.Context) error) error {
	task := &implTask{
		cfg: cfg,
		fn:  fn,
	}
	return o.observe(task)
}

// RunFunc executes a function with the DefaultTaskConfig and observes its execution.
// All execution metrics (duration, success/failure, panic, etc) will be automatically recorded.
// If a [context.DeadlineExceeded] error is returned, it is recorded as a timeout error.
// When RecoverPanics is true, returns ErrPanicOccurred if a panic occurs and is recovered.
func (o *Observer) RunFunc(fn func() error) error {
	task := &implTask{
		cfg: o.defaultTaskConfig(),
		fn: func(ctx context.Context) error {
			return fn() // ignore ctx
		},
	}
	return o.observe(task)
}

// RunTask executes a [Task] implementation and observes its execution.
// All execution metrics (duration, success/failure, retries, etc) will be automatically recorded.
// The task.Config() method determines the execution behavior (timeout, retries, concurrency, etc).
// When RecoverPanics is true, returns ErrPanicOccurred if a panic occurs and is recovered.
func (o *Observer) RunTask(task Task) error {
	t := &implTask{
		cfg: task.Config(),
		fn:  task.Execute,
	}
	return o.observe(t)
}

// observe is the internal method that observes task execution.
// This method manages the InFlight gauge for individual tasks.
// Task execution and retries are handled by [Observer.executeTask].
func (o *Observer) observe(task *implTask) (err error) {
	if o.metrics == nil {
		return errors.New("observer metrics not configured")
	}
	o.metrics.InFlight.Inc()
	defer o.metrics.InFlight.Dec()

	if !task.Config().Concurrent {
		return o.executeTask(task)
	} else {
		go func() {
			_ = o.executeTask(task)
		}()
	}
	return nil
}

// executeTask performs the task execution logic and handles retries.
// Retry attempts are call method recursively for synchronous task handling.
// If panic occurs, the error from task.Execute() is switched for ErrPanicOccurred.
// This follows the behaviour defined by the [TaskConfig] task.Config() and [Task.Execute].
func (o *Observer) executeTask(task *implTask) error {

	// Configure timeout
	var ctx = context.Background()
	if task.Config().Timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, task.Config().Timeout)
		defer cancel()
	}

	// Run task in closure to capture the panic
	var panicValue interface{}
	err := func() (err error) {
		start := time.Now()
		defer func() {
			o.metrics.ObservedRuntimes.Observe(
				time.Since(start).Seconds(),
			)
			if r := recover(); r != nil {
				panicValue = r
				err = ErrPanicOccurred{panic: r}
			}
		}()
		err = task.Execute(ctx)
		return err
	}()

	// Handle errors
	if err != nil {
		o.metrics.Errors.Inc()
		if errors.Is(err, context.DeadlineExceeded) {
			o.metrics.TimeoutErrors.Inc()
		}

		// Handle panics
		if panicValue != nil {
			o.metrics.Panics.Inc()
			if !task.Config().RecoverPanics {
				panic(panicValue) // re-throw panic
			}
		}

		// Handle retries
		if task.Config().MaxRetries > 0 {
			cfg := task.Config()

			// Maximum retries reached
			if task.retryCount >= cfg.MaxRetries {
				return err
			} else {
				o.metrics.Retries.Inc()
			}

			// Try circuit break
			if cfg.RetryCircuitBreaker != nil {
				if cfg.RetryCircuitBreaker(err) {
					return err
				}
			}
			// Wait retry duration
			if cfg.RetryStrategy != nil {
				wait := cfg.RetryStrategy(task.retryCount)
				if wait > 0 {
					time.Sleep(wait)
				}
			}

			// Next retry attempt
			retryTask := &implTask{
				fn:         task.Execute,
				cfg:        cfg,
				retryCount: task.retryCount + 1,
			}

			// Run retry task
			if !retryTask.Config().Concurrent {
				err2 := o.observe(retryTask)
				if err2 != nil {
					return errors.Join(err, err2)
				} else {
					// recursive was successful
					return nil
				}
			} else {
				go func() {
					_ = o.observe(retryTask)
				}()
			}
		}
	} else {
		o.metrics.Successes.Inc()
	}

	return err
}

// defaultTaskConfig returns the default task configuration for the Observer.
func (o *Observer) defaultTaskConfig() TaskConfig {
	if o.cfg.DefaultTaskConfig != nil {
		return *o.cfg.DefaultTaskConfig
	}
	return defaultTaskConfig()
}
