package sentinel

import (
	"github.com/prometheus/client_golang/prometheus"
)

// PrometheusOption defines metric configurations for an [Observer].
// Options are provided to [NewObserver] on setting up the Observer.
type PrometheusOption func(*observerConfig)

// observerConfig defines the configuration for a [Observer].
type observerConfig struct {
	namespace     string
	subsystem     string
	description   string
	buckets       []float64
	constLabels   prometheus.Labels
	trackRetries  bool
	trackTimeouts bool
}

// WithNamespace sets the Prometheus namespace for all metrics generated by this observer.
// For example, "myapp" with no subsystem results in metrics like "myapp_success_total".
// If empty with subsystem, no namespace prefix is used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithNamespace("myapp"),
//	)
func WithNamespace(namespace string) PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the Prometheus subsystem for all metrics generated by this observer.
// For example, "workers" with no namespace results in metrics like "workers_success_total".
// If empty with namespace, defaults to "sentinel" if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSubsystem("workers"),
//	)
func WithSubsystem(subsystem string) PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated metrics to
// describe what type of tasks are being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" to convey a generic process if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDescription("background processes"),
//	)
func WithDescription(description string) PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.description = description
	}
}

// WithDurationMetrics enables histogram durations metrics for the Observer.
// Buckets are specified in seconds with generated buckets range between 0 and math.Inf.
// For each observed runtime of a task, it is recorded to one of the specified buckets.
// Please refer to [prometheus.HistogramOpts].Buckets for more information.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDurationMetrics([]float64{0.05, 1, 5, 30, 600}),
//	)
func WithDurationMetrics(buckets []float64) PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.buckets = buckets
	}
}

// TODO: redo docs.
// WithTimeoutMetrics enables timeout-specific metrics tracking.
// When enabled, a separate "timeouts_total" metric is created to track tasks that
// failed due to context deadline exceeded. This provides visibility into timeout
// occurrences separate from general errors, allowing for better monitoring of
// timeout-related issues.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithTimeoutMetrics(),
//	)
func WithTimeoutMetrics() PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.trackTimeouts = true
	}
}

// TODO: redo docs.
// WithRetryMetrics enables comprehensive retry observability metrics.
// When enabled, both "retries_total" and "failures_total" metrics are created to provide
// complete visibility into retry behavior. The "retries_total" metric tracks individual
// retry attempts, while "failures_total" tracks tasks that ultimately failed after
// exhausting all retry attempts. This provides visibility into retry effectiveness and
// distinguishes between transient failures (resolved by retries) and persistent failures.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithRetryMetrics(),
//	)
func WithRetryMetrics() PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.trackRetries = true
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By convention, ConstLabels are not a recommended practice for Prometheus metrics.
// For more information, please refer to [prometheus.Opts].ConstLabels documentation.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithConstLabels(prometheus.Labels{"env": "production"}),
//	)
func WithConstLabels(labels prometheus.Labels) PrometheusOption {
	return func(cfg *observerConfig) {
		cfg.constLabels = labels
	}
}
