package sentinel

import (
	"github.com/prometheus/client_golang/prometheus"
)

type observerConfig struct {
	namespace       string
	subsystem       string
	description     string
	bucketDurations []float64
	constLabels     prometheus.Labels
	taskConfig      *TaskConfig
	recoverPanics   bool
	trackFailures   bool
}

// ObserverOption defines a configuration option for an Observer.
// Options are provided to [NewObserver] on setting up the Observer.
type ObserverOption func(*observerConfig)

// WithNamespace sets the Prometheus namespace for all metrics generated by this observer.
// For example, "myapp" with no subsystem results in metrics like "myapp_successes_total".
// If empty with subsystem, no namespace prefix is used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithNamespace("myapp"),
//	)
func WithNamespace(namespace string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the Prometheus subsystem for all metrics generated by this observer.
// For example, "workers" with no namespace results in metrics like "workers_successes_total".
// If empty with namespace, defaults to "sentinel" if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithSubsystem("workers"),
//	)
func WithSubsystem(subsystem string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated metrics to
// describe what type of tasks are being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" to convey a generic process if not specified.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDescription("background processes"),
//	)
func WithDescription(description string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.description = description
	}
}

// WithHistogramBuckets enables histogram durations metrics for the Observer.
// Buckets are specified in seconds with generated buckets range between 0 and math.Inf.
// For each observed runtime of a task, it is recorded to one of the specified buckets.
// Please refer to [prometheus.HistogramOpts].Buckets for more information.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithHistogramBuckets([]float64{0.05, 1, 5, 30, 600}),
//	)
func WithHistogramBuckets(buckets []float64) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.bucketDurations = buckets
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By convention, ConstLabels are not a recommended practice for Prometheus metrics.
// For more information, please refer to [prometheus.Opts].ConstLabels documentation.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithConstLabels(prometheus.Labels{"env": "production"}),
//	)
func WithConstLabels(labels prometheus.Labels) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.constLabels = labels
	}
}

// WithDefaultTaskConfig sets the default [TaskConfig] for calls to [Observer.RunFunc]
// and [Observer.RunFuncCtx] where task configuration is not specified through method
// calls. By default, a basic task configuration without retry attempts will be used.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithDefaultTaskConfig(&sentinel.TaskConfig{
//	        Timeout: 10 * time.Second,
//	        MaxRetries: 3,
//	    }),
//	)
func WithDefaultTaskConfig(taskConfig *TaskConfig) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.taskConfig = taskConfig
	}
}

// DisablePanicRecovery disables automatic panic recovery leaving panics to propagate.
// Default observer behaviour is to recover and return panics as [ErrRecoveredPanic]
// errors. Panic occurrences will always be recorded as errors and panics in metrics
// regardless of this observer option.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.DisablePanicRecovery(),
//	)
func DisablePanicRecovery() ObserverOption {
	return func(cfg *observerConfig) {
		cfg.recoverPanics = false
	}
}

// WithFailuresTracking enables tracking of persistent failures after all retry attempts.
// When enabled, a separate "failures_total" metric which increments when tasks fail
// persistently. This differs from the "errors_total" metric which increments whenever
// tasks fail or when panics occur.
//
// Example usage:
//
//	observer := sentinel.NewObserver(
//	    sentinel.WithFailuresTracking(),
//	)
func WithFailuresTracking() ObserverOption {
	return func(cfg *observerConfig) {
		cfg.trackFailures = true
	}
}
