package sentinel

import (
	"github.com/prometheus/client_golang/prometheus"
)

type observerConfig struct {
	namespace       string
	subsystem       string
	description     string
	bucketDurations []float64
	constLabels     prometheus.Labels
	taskConfig      *TaskConfig
	recoverPanics   bool
}

// ObserverOption defines an configuration option for an Observer.
// Options are provided to [NewObserver] on setting up the Observer.
type ObserverOption func(*observerConfig)

// WithNamespace sets the Prometheus namespace for all metrics generated by this observer.
// For example, "myapp" results in metrics like "myapp_successes_total".
// If empty with subsystem, no namespace prefix is used.
func WithNamespace(namespace string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.namespace = namespace
	}
}

// WithSubsystem sets the Prometheus subsystem for all metrics generated by this observer.
// For example, "workers" results in metrics like "workers_successes_total".
// If empty with namespace, defaults to "sentinel" if not specified.
func WithSubsystem(subsystem string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.subsystem = subsystem
	}
}

// WithDescription sets the description used in the help text for generated metrics to
// describe what type of tasks are being observed. For example, "background processes"
// results in help text like: "Number of successes from observed background processes".
// Defaults to "tasks" if not specified.
func WithDescription(description string) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.description = description
	}
}

// WithHistogramBuckets sets histogram bucket durations for the Observer.
// If not specified, no histogram metrics will be recorded or exported by the Observer.
// Each bucket duration is a float64 representing seconds where final buckets between 0 and math.Inf
// will be included after. Each recorded task duration is assigned within one of the specified buckets.
//
// Example usage:
//
//	observer := sentinel.NewObserver(sentinel.WithHistogramBuckets([]float64{0.05, 1, 5, 30, 600}))
//
// Please refer to [prometheus.HistogramOpts].Buckets for more information.
func WithHistogramBuckets(buckets []float64) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.bucketDurations = buckets
	}
}

// WithConstLabels sets constant labels to exported metrics from the Observer.
// By default, no labels are attached. Please refer to [prometheus.Opts].ConstLabels
// for more information.
func WithConstLabels(labels prometheus.Labels) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.constLabels = labels
	}
}

// WithDefaultTaskConfig sets the default [TaskConfig] for calls to [Observer.RunFunc].
// If not specified, a basic task configuration without retry attempts will be used.
func WithDefaultTaskConfig(taskConfig *TaskConfig) ObserverOption {
	return func(cfg *observerConfig) {
		cfg.taskConfig = taskConfig
	}
}

// DisablePanicRecovery disables automatic panic recovery.
// By default, panics are recovered and returned as [ErrRecoveredPanic] errors.
// Panic occurrences are always recorded in metrics regardless of this observer option.
func DisablePanicRecovery() ObserverOption {
	return func(cfg *observerConfig) {
		cfg.recoverPanics = false
	}
}
