global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'workerloop'
    static_configs:
      - targets: ['workerloop:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
